package com.ruoyi.fund.controller;
import java.util.List; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.validation.annotation.Validated; import org.springframework.web.bind.annotation.*; import com.ruoyi.common.core.web.controller.BaseController; import com.ruoyi.common.core.web.domain.AjaxResult; import com.ruoyi.common.core.web.page.TableDataInfo; import com.ruoyi.common.log.annotation.Log; import com.ruoyi.common.log.enums.BusinessType; import com.ruoyi.common.security.annotation.RequiresPermissions; import com.ruoyi.fund.domain.*; import com.ruoyi.fund.domain.dto.FundFinishRequest; import com.ruoyi.fund.service.IFundUseService;
@RestController @RequestMapping("/use") public class FundUseController extends BaseController { @Autowired private IFundUseService service; @Autowired private com.ruoyi.fund.service.IFundBudgetService budgetService;
 @GetMapping("/overview/{groupId}") public AjaxResult overview(@PathVariable Long groupId){return AjaxResult.success(budgetService.useOverview(groupId));}
 @RequiresPermissions("fund:use:list") @GetMapping("/plan/list") public TableDataInfo list(FundUsePlan q){startPage();List<FundUsePlan> l=service.selectPlanList(q);return getDataTable(l);} @GetMapping("/plan/{id}") public AjaxResult get(@PathVariable Long id){return AjaxResult.success(service.selectPlan(id));}
 @RequiresPermissions("fund:use:add") @Log(title="资金使用计划",businessType=BusinessType.INSERT) @PostMapping("/plan") public AjaxResult add(@Validated @RequestBody FundUsePlan p){return toAjax(service.insertPlan(p));}
 @RequiresPermissions("fund:use:edit") @Log(title="资金使用计划",businessType=BusinessType.UPDATE) @PutMapping("/plan") public AjaxResult edit(@Validated @RequestBody FundUsePlan p){return toAjax(service.updatePlan(p));}
 @RequiresPermissions("fund:use:remove") @Log(title="资金使用计划",businessType=BusinessType.DELETE) @DeleteMapping("/plan/{id}") public AjaxResult del(@PathVariable Long id){return toAjax(service.deletePlan(id));}
 @GetMapping("/plan/{id}/records") public AjaxResult records(@PathVariable Long id){return AjaxResult.success(service.selectRecords(id));}
 @RequiresPermissions("fund:use:submit") @Log(title="资金使用记录",businessType=BusinessType.INSERT) @PostMapping("/record") public AjaxResult addRecord(@Validated @RequestBody FundUseRecord r){return toAjax(service.insertRecord(r));}
 @RequiresPermissions("fund:use:submit") @Log(title="资金使用记录",businessType=BusinessType.UPDATE) @PutMapping("/record") public AjaxResult editRecord(@Validated @RequestBody FundUseRecord r){return toAjax(service.updateRecord(r));}
 @RequiresPermissions("fund:use:submit") @Log(title="资金使用记录",businessType=BusinessType.DELETE) @DeleteMapping("/record/{id}") public AjaxResult delRecord(@PathVariable Long id){return toAjax(service.deleteRecord(id));}
 @RequiresPermissions("fund:use:finish") @GetMapping("/plan/{id}/finish-check") public AjaxResult finishCheck(@PathVariable Long id){return AjaxResult.success(service.finishCheck(id));}
 @RequiresPermissions("fund:use:finish") @PutMapping("/plan/{id}/finish") public AjaxResult finish(@PathVariable Long id,@RequestBody FundFinishRequest r){service.finish(id,r);return AjaxResult.success();}
 @RequiresPermissions("fund:use:finish") @PutMapping("/plan/{id}/force-finish/confirm") public AjaxResult confirmForceFinish(@PathVariable Long id){service.confirmForceFinish(id);return AjaxResult.success();}
}
