package com.ruoyi.fund.controller;
import java.util.List; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.validation.annotation.Validated; import org.springframework.web.bind.annotation.*; import com.ruoyi.common.core.web.controller.BaseController; import com.ruoyi.common.core.web.domain.AjaxResult; import com.ruoyi.common.core.web.page.TableDataInfo; import com.ruoyi.common.log.annotation.Log; import com.ruoyi.common.log.enums.BusinessType; import com.ruoyi.common.security.annotation.RequiresPermissions; import com.ruoyi.fund.domain.*; import com.ruoyi.fund.domain.dto.*; import com.ruoyi.fund.service.IFundAllocationService;
@RestController @RequestMapping("/allocation") public class FundAllocationController extends BaseController { @Autowired private IFundAllocationService service;
 @GetMapping("/plan/list") public TableDataInfo list(FundAllocationPlan q){startPage();List<FundAllocationPlan> l=service.selectPlanList(q);return getDataTable(l);} @GetMapping("/plan/{id}") public AjaxResult get(@PathVariable Long id){return AjaxResult.success(service.selectPlan(id));}
 @RequiresPermissions("fund:allocation:add") @Log(title="资金拨付计划",businessType=BusinessType.INSERT) @PostMapping("/plan") public AjaxResult add(@Validated @RequestBody FundAllocationPlan p){return toAjax(service.insertPlan(p));}
 @RequiresPermissions("fund:allocation:edit") @Log(title="资金拨付计划",businessType=BusinessType.UPDATE) @PutMapping("/plan") public AjaxResult edit(@Validated @RequestBody FundAllocationPlan p){return toAjax(service.updatePlan(p));}
 @RequiresPermissions("fund:allocation:remove") @Log(title="资金拨付计划",businessType=BusinessType.DELETE) @DeleteMapping("/plan/{id}") public AjaxResult del(@PathVariable Long id){return toAjax(service.deletePlan(id));}
 @RequiresPermissions("fund:allocation:assign") @PutMapping("/plan/{id}/assign") public AjaxResult assign(@PathVariable Long id,@RequestBody FundAssignRequest r){return toAjax(service.assign(id,r.getResponsibleUserId()));}
 @GetMapping("/plan/{id}/records") public AjaxResult records(@PathVariable Long id){return AjaxResult.success(service.selectRecords(id));}
 @RequiresPermissions("fund:allocation:submit") @Log(title="资金拨付记录",businessType=BusinessType.INSERT) @PostMapping("/record") public AjaxResult addRecord(@Validated @RequestBody FundAllocationRecord r){return toAjax(service.insertRecord(r));}
 @RequiresPermissions("fund:allocation:submit") @Log(title="资金拨付记录",businessType=BusinessType.UPDATE) @PutMapping("/record") public AjaxResult editRecord(@Validated @RequestBody FundAllocationRecord r){return toAjax(service.updateRecord(r));}
 @RequiresPermissions("fund:allocation:submit") @Log(title="资金拨付记录",businessType=BusinessType.DELETE) @DeleteMapping("/record/{id}") public AjaxResult delRecord(@PathVariable Long id){return toAjax(service.deleteRecord(id));}
 @RequiresPermissions("fund:allocation:finish") @GetMapping("/plan/{id}/finish-check") public AjaxResult finishCheck(@PathVariable Long id){return AjaxResult.success(service.finishCheck(id));}
 @RequiresPermissions("fund:allocation:finish") @PutMapping("/plan/{id}/finish") public AjaxResult finish(@PathVariable Long id,@RequestBody FundFinishRequest r){service.finish(id,Boolean.TRUE.equals(r.getConfirmDifference()));return AjaxResult.success();}
}
