package com.ruoyi.fund.service.impl;
import java.math.BigDecimal; import java.util.List;
import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Isolation; import org.springframework.transaction.annotation.Transactional; import com.ruoyi.common.core.exception.ServiceException; import com.ruoyi.common.security.utils.SecurityUtils;
import com.ruoyi.fund.constant.FundConstants; import com.ruoyi.fund.domain.FundProjectBudget; import com.ruoyi.fund.domain.vo.FundAllocationOverviewVo; import com.ruoyi.fund.domain.vo.FundUseOverviewVo;
import com.ruoyi.fund.mapper.*; import com.ruoyi.fund.service.*;
@Service
public class FundBudgetServiceImpl implements IFundBudgetService {
 @Autowired private FundProjectBudgetMapper mapper; @Autowired private FundAllocationPlanMapper allocationPlanMapper; @Autowired private FundAllocationRecordMapper allocationRecordMapper; @Autowired private FundUsePlanMapper usePlanMapper; @Autowired private FundUseRecordMapper useRecordMapper; @Autowired private IFundResearchService researchService; @Autowired private FundPermissionService permissionService;
 public FundProjectBudget selectById(Long id){return enrich(mapper.selectById(id));} public FundProjectBudget selectByTopicId(Long id){return enrich(mapper.selectByTopicId(id));} public List<FundProjectBudget> selectList(FundProjectBudget q){List<FundProjectBudget> list=mapper.selectList(q);for(FundProjectBudget b:list)enrich(b);return list;}
 @Transactional(isolation=Isolation.READ_COMMITTED) public int insert(FundProjectBudget b){assertAdmin();researchService.getGroup(b.getTopicId());if(mapper.selectByTopicId(b.getTopicId())!=null)throw new ServiceException("该课题已配置总资金");validate(b.getTotalAmount());b.setStatus(FundConstants.STATUS_RUNNING);b.setCreateBy(SecurityUtils.getUsername());return mapper.insert(b);}
 @Transactional(isolation=Isolation.READ_COMMITTED) public int update(FundProjectBudget b){assertAdmin();FundProjectBudget hint=mapper.selectById(b.getBudgetId());if(hint==null)throw new ServiceException("总资金配置不存在");FundProjectBudget old=mapper.selectByTopicIdForUpdate(hint.getTopicId());if(old==null||!old.getBudgetId().equals(b.getBudgetId()))throw new ServiceException("总资金配置不存在或已发生变更");validate(b.getTotalAmount());BigDecimal allocationPlanned=nz(allocationPlanMapper.sumPlanAmount(old.getTopicId(),null));if(b.getTotalAmount().compareTo(allocationPlanned)<0)throw new ServiceException("课题总资金不能低于已有拨付计划总额："+allocationPlanned);BigDecimal usePlanned=nz(usePlanMapper.sumPlanAmount(old.getTopicId(),null));if(b.getTotalAmount().compareTo(usePlanned)<0)throw new ServiceException("课题总资金不能低于已有使用计划总额："+usePlanned);BigDecimal allocationActual=nz(allocationRecordMapper.sumByTopicId(old.getTopicId()));if(b.getTotalAmount().compareTo(allocationActual)<0)throw new ServiceException("课题总资金不能低于已有实际拨付总额："+allocationActual);BigDecimal useActual=nz(useRecordMapper.sumByTopicId(old.getTopicId()));if(b.getTotalAmount().compareTo(useActual)<0)throw new ServiceException("课题总资金不能低于已有实际使用总额："+useActual);b.setUpdateBy(SecurityUtils.getUsername());return mapper.update(b);}
 @Transactional(isolation=Isolation.READ_COMMITTED) public int delete(Long id){assertAdmin();FundProjectBudget hint=mapper.selectById(id);if(hint==null)return 0;FundProjectBudget b=mapper.selectByTopicIdForUpdate(hint.getTopicId());if(b==null||!b.getBudgetId().equals(id))return 0;if(allocationPlanMapper.countByTopicId(b.getTopicId())>0||usePlanMapper.countByTopicId(b.getTopicId())>0)throw new ServiceException("已有拨付或使用计划，不能删除总资金配置");return mapper.deleteById(id);}
 public FundAllocationOverviewVo allocationOverview(Long groupId){FundProjectBudget b=requiredBudget(groupId);FundAllocationOverviewVo v=new FundAllocationOverviewVo();v.setGroupId(groupId);v.setTotalAmount(nz(b.getTotalAmount()));v.setPlannedAllocation(nz(allocationPlanMapper.sumPlanAmount(groupId,null)));v.setActualAllocation(nz(allocationRecordMapper.sumByTopicId(groupId)));v.setRemainingAllocation(nonNegative(v.getTotalAmount().subtract(v.getActualAllocation())));return v;}
 public FundUseOverviewVo useOverview(Long groupId){permissionService.assertGroupMember(groupId,SecurityUtils.getUserId());requiredBudget(groupId);FundUseOverviewVo v=new FundUseOverviewVo();v.setGroupId(groupId);v.setPlannedUse(nz(usePlanMapper.sumPlanAmount(groupId,null)));v.setActualUse(nz(useRecordMapper.sumByTopicId(groupId)));v.setRemainingUse(nonNegative(v.getPlannedUse().subtract(v.getActualUse())));v.setOverspend(nonNegative(v.getActualUse().subtract(v.getPlannedUse())));return v;}
 private FundProjectBudget enrich(FundProjectBudget b){if(b!=null)b.setTopicName(researchService.getGroup(b.getTopicId()).getGroupName());return b;}
 private FundProjectBudget requiredBudget(Long groupId){FundProjectBudget b=mapper.selectByTopicId(groupId);if(b==null)throw new ServiceException("该课题尚未配置总资金");return b;}
 private void validate(BigDecimal a){if(a==null||a.compareTo(BigDecimal.ZERO)<=0)throw new ServiceException("课题总资金必须大于0");} private BigDecimal nz(BigDecimal x){return x==null?BigDecimal.ZERO:x;} private BigDecimal nonNegative(BigDecimal x){return x.compareTo(BigDecimal.ZERO)<0?BigDecimal.ZERO:x;} private void assertAdmin(){permissionService.assertAdmin("维护课题总资金");}
}
