package com.ruoyi.fund.service.impl;
import java.math.BigDecimal; import java.util.List;
import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.ruoyi.common.core.exception.ServiceException; import com.ruoyi.common.security.utils.SecurityUtils;
import com.ruoyi.fund.util.FundSecurityUtils; import com.ruoyi.fund.constant.FundConstants; import com.ruoyi.fund.domain.FundProjectBudget; import com.ruoyi.fund.domain.FundTopic; import com.ruoyi.fund.domain.vo.FundOverviewVo;
import com.ruoyi.fund.mapper.*; import com.ruoyi.fund.service.*;
@Service
public class FundBudgetServiceImpl implements IFundBudgetService {
 @Autowired private FundProjectBudgetMapper mapper; @Autowired private FundAllocationPlanMapper allocationPlanMapper; @Autowired private FundAllocationRecordMapper allocationRecordMapper; @Autowired private FundUsePlanMapper usePlanMapper; @Autowired private FundUseRecordMapper useRecordMapper; @Autowired private IFundTopicService topicService;
 public FundProjectBudget selectById(Long id){return mapper.selectById(id);} public FundProjectBudget selectByTopicId(Long id){return mapper.selectByTopicId(id);} public List<FundProjectBudget> selectList(FundProjectBudget q){return mapper.selectList(q);}
 @Transactional public int insert(FundProjectBudget b){assertAdmin(); FundTopic t=topicService.selectById(b.getTopicId());if(t==null)throw new ServiceException("课题不存在");if(mapper.selectByTopicId(b.getTopicId())!=null)throw new ServiceException("该课题已配置总资金");validate(b.getTotalAmount());b.setStatus(FundConstants.STATUS_RUNNING);b.setCreateBy(SecurityUtils.getUsername());return mapper.insert(b);}
 @Transactional public int update(FundProjectBudget b){assertAdmin();FundProjectBudget old=mapper.selectById(b.getBudgetId());if(old==null)throw new ServiceException("总资金配置不存在");mapper.selectByTopicIdForUpdate(old.getTopicId());validate(b.getTotalAmount());BigDecimal planned=nz(allocationPlanMapper.sumPlanAmount(old.getTopicId(),null));if(b.getTotalAmount().compareTo(planned)<0)throw new ServiceException("课题总资金不能低于已有拨付计划总额："+planned);b.setUpdateBy(SecurityUtils.getUsername());return mapper.update(b);}
 public int delete(Long id){assertAdmin();FundProjectBudget b=mapper.selectById(id);if(b==null)return 0;if(allocationPlanMapper.countByTopicId(b.getTopicId())>0||usePlanMapper.countByTopicId(b.getTopicId())>0)throw new ServiceException("已有拨付或使用计划，不能删除总资金配置");return mapper.deleteById(id);}
 public FundOverviewVo overview(Long topicId){FundProjectBudget b=mapper.selectByTopicId(topicId);if(b==null)throw new ServiceException("该课题尚未配置总资金");FundOverviewVo v=new FundOverviewVo();v.setTopicId(topicId);v.setTopicName(b.getTopicName());v.setTotalAmount(nz(b.getTotalAmount()));v.setPlannedAllocationAmount(nz(allocationPlanMapper.sumPlanAmount(topicId,null)));v.setArrivedAmount(nz(allocationRecordMapper.sumByTopicId(topicId)));v.setUsedAmount(nz(useRecordMapper.sumByTopicId(topicId)));v.setPendingAllocationAmount(v.getTotalAmount().subtract(v.getArrivedAmount()));v.setRemainingUseAmount(v.getTotalAmount().subtract(v.getUsedAmount()));return v;}
 private void validate(BigDecimal a){if(a==null||a.compareTo(BigDecimal.ZERO)<=0)throw new ServiceException("课题总资金必须大于0");} private BigDecimal nz(BigDecimal x){return x==null?BigDecimal.ZERO:x;} private void assertAdmin(){if(!FundSecurityUtils.isSystemAdmin())throw new ServiceException("仅系统管理员可维护课题总资金");}
}
