package com.ruoyi.fund.service.impl;
import static com.ruoyi.fund.constant.FundAuditConstants.*;
import java.math.BigDecimal; import java.util.ArrayList; import java.util.List; import java.util.Objects;
import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Isolation; import org.springframework.transaction.annotation.Transactional;
import com.ruoyi.common.core.exception.ServiceException; import com.ruoyi.common.security.utils.SecurityUtils;
import com.ruoyi.fund.constant.FundConstants; import com.ruoyi.fund.domain.*; import com.ruoyi.fund.domain.dto.FundFinishRequest; import com.ruoyi.fund.domain.vo.FundFinishCheckVo; import com.ruoyi.fund.mapper.*; import com.ruoyi.fund.service.*; import com.ruoyi.system.api.domain.*;
import com.ruoyi.research.api.domain.ResearchGroupMemberDto;
@Service
public class FundAllocationServiceImpl implements IFundAllocationService {
 @Autowired private FundAllocationPlanMapper planMapper; @Autowired private FundAllocationRecordMapper recordMapper; @Autowired private FundUseRecordMapper useRecordMapper; @Autowired private FundProjectBudgetMapper budgetMapper; @Autowired private IFundOrgService org; @Autowired private IFundResearchService researchService; @Autowired private IFundOperationLogService audit; @Autowired private IFundAttachmentService attachmentService; @Autowired private FundPermissionService permissionService;
 public List<FundAllocationPlan> selectPlanList(FundAllocationPlan q){if(q.getTopicId()==null)throw new ServiceException("请选择课题");permissionService.assertGroupMember(q.getTopicId(),SecurityUtils.getUserId());List<FundAllocationPlan> list=planMapper.selectList(q);for(FundAllocationPlan p:list)enrichPlan(p);return list;} public FundAllocationPlan selectPlan(Long id){FundAllocationPlan p=requiredPlan(id);permissionService.assertGroupMember(p.getTopicId(),SecurityUtils.getUserId());return enrichPlan(p);}
 @Transactional(isolation=Isolation.READ_COMMITTED) public int insertPlan(FundAllocationPlan p){assertAdmin();FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(p.getTopicId());if(b==null)throw new ServiceException("请先配置课题总资金");enrichDepts(p);validatePlanAmount(p.getTopicId(),null,p.getPlanAmount(),b.getTotalAmount());p.setBudgetId(b.getBudgetId());p.setStatus(FundConstants.STATUS_RUNNING);p.setCreateBy(SecurityUtils.getUsername());int rows=planMapper.insert(p);if(rows>0)audit.record(p.getTopicId(),ALLOCATION_PLAN,p.getPlanId(),CREATE_PLAN,null,planMapper.selectById(p.getPlanId()),null);return rows;}
 @Transactional(isolation=Isolation.READ_COMMITTED) public int updatePlan(FundAllocationPlan p){assertAdmin();FundAllocationPlan hint=requiredPlan(p.getPlanId());FundProjectBudget b=requiredLockedBudget(hint.getTopicId());FundAllocationPlan old=requiredLockedPlan(p.getPlanId(),hint.getTopicId());assertRunning(old);p.setTopicId(old.getTopicId());assertAllocationFieldsUnlocked(old,p);enrichDepts(p);validatePlanAmount(old.getTopicId(),old.getPlanId(),p.getPlanAmount(),b.getTotalAmount());p.setUpdateBy(SecurityUtils.getUsername());int rows=planMapper.update(p);if(rows>0){FundAllocationPlan after=planMapper.selectById(p.getPlanId());audit.record(old.getTopicId(),ALLOCATION_PLAN,p.getPlanId(),UPDATE_PLAN,old,after,null);if(!sameAmount(old.getPlanAmount(),after.getPlanAmount()))audit.record(old.getTopicId(),ALLOCATION_PLAN,p.getPlanId(),CHANGE_PLAN_AMOUNT,old,after,null);}return rows;}
 @Transactional(isolation=Isolation.READ_COMMITTED) public int deletePlan(Long id){assertAdmin();FundAllocationPlan hint=requiredPlan(id);requiredLockedBudget(hint.getTopicId());FundAllocationPlan p=requiredLockedPlan(id,hint.getTopicId());assertRunning(p);if(recordMapper.countByPlanId(id)>0)throw new ServiceException("计划已有拨付记录，不能删除");return planMapper.deleteById(id);}
 @Transactional public int assign(Long id,Long uid){FundAllocationPlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("拨付计划不存在");assertRunning(p);Long current=SecurityUtils.getUserId();permissionService.assertCanAssignAllocation(p,current);String name=null;if(uid!=null){FundUserOption u=org.getUser(uid);if(!researchService.isGroupUnitMember(p.getTopicId(),p.getAllocationDeptId(),uid))throw new ServiceException("责任人必须是当前课题拨付单位成员");name=display(u);}int rows=planMapper.assign(id,uid,name,SecurityUtils.getUsername());if(rows>0&&!Objects.equals(p.getResponsibleUserId(),uid))audit.record(p.getTopicId(),ALLOCATION_PLAN,id,p.getResponsibleUserId()==null?ASSIGN_RESPONSIBLE:CHANGE_RESPONSIBLE,p,planMapper.selectById(id),null);return rows;}
 public List<FundUserOption> selectCandidateUsers(Long planId){FundAllocationPlan p=requiredPlan(planId);permissionService.assertCanAssignAllocation(p,SecurityUtils.getUserId());List<FundUserOption> users=new ArrayList<>();for(ResearchGroupMemberDto member:researchService.getSelectableMembers(p.getTopicId(),p.getAllocationDeptId())){FundUserOption user=new FundUserOption();user.setUserId(member.getUserId());user.setDeptId(member.getDeptId());user.setUserName(member.getUserName());user.setNickName(member.getNickName());users.add(user);}return users;}
 public List<FundAllocationRecord> selectRecords(Long planId){FundAllocationPlan p=requiredPlan(planId);Long userId=SecurityUtils.getUserId();permissionService.assertGroupMember(p.getTopicId(),userId);boolean canOperate=FundConstants.STATUS_RUNNING.equals(p.getStatus())&&permissionService.canOperateAllocation(p,userId);List<FundAllocationRecord> records=recordMapper.selectByPlanId(planId);for(FundAllocationRecord record:records){enrichAttachments(record);record.setCanEdit(canOperate&&permissionService.canEditRecord(record.getSubmitUserId(),userId));}return records;}
 @Transactional(isolation=Isolation.READ_COMMITTED) public int insertRecord(FundAllocationRecord r){FundAllocationPlan hint=requiredPlan(r.getPlanId());FundProjectBudget b=requiredLockedBudget(hint.getTopicId());FundAllocationPlan p=requiredLockedPlan(r.getPlanId(),hint.getTopicId());assertRunning(p);assertOperate(p);validateAmount(r.getAmount());assertNoLegacyVoucherUrls(r.getVoucherUrls());BigDecimal current=nz(recordMapper.sumByTopicId(p.getTopicId()));assertAllocationTotals(current.add(r.getAmount()),nz(useRecordMapper.sumByTopicId(p.getTopicId())),b.getTotalAmount());String attachmentTokens=r.getAttachmentTokens();r.setVoucherUrls(null);r.setSubmitUserId(SecurityUtils.getUserId());r.setSubmitUserName(SecurityUtils.getUsername());r.setCreateBy(SecurityUtils.getUsername());int rows=recordMapper.insert(r);if(rows>0){attachmentService.consume(p.getTopicId(),ALLOCATION_RECORD,r.getRecordId(),attachmentTokens);audit.record(p.getTopicId(),ALLOCATION_RECORD,r.getRecordId(),CREATE_RECORD,null,enrichAttachments(recordMapper.selectById(r.getRecordId())),null);}return rows;}
 @Transactional(isolation=Isolation.READ_COMMITTED) public int updateRecord(FundAllocationRecord r){FundAllocationRecord hintRecord=requiredRecord(r.getRecordId());FundAllocationPlan hintPlan=requiredPlan(hintRecord.getPlanId());FundProjectBudget b=requiredLockedBudget(hintPlan.getTopicId());FundAllocationPlan p=requiredLockedPlan(hintRecord.getPlanId(),hintPlan.getTopicId());FundAllocationRecord old=requiredLockedRecord(r.getRecordId(),p.getPlanId());assertRunning(p);assertOperate(p);assertOwn(old.getSubmitUserId());validateAmount(r.getAmount());assertNoLegacyVoucherUrls(r.getVoucherUrls());BigDecimal after=nz(recordMapper.sumByTopicId(p.getTopicId())).subtract(nz(old.getAmount())).add(r.getAmount());assertAllocationTotals(after,nz(useRecordMapper.sumByTopicId(p.getTopicId())),b.getTotalAmount());enrichAttachments(old);String attachmentTokens=r.getAttachmentTokens();r.setUpdateBy(SecurityUtils.getUsername());int rows=recordMapper.update(r);if(rows>0){attachmentService.consume(p.getTopicId(),ALLOCATION_RECORD,r.getRecordId(),attachmentTokens);audit.record(p.getTopicId(),ALLOCATION_RECORD,r.getRecordId(),UPDATE_RECORD,old,enrichAttachments(recordMapper.selectById(r.getRecordId())),null);}return rows;}
 @Transactional(isolation=Isolation.READ_COMMITTED) public int deleteRecord(Long id){FundAllocationRecord hintRecord=recordMapper.selectById(id);if(hintRecord==null)return 0;FundAllocationPlan hintPlan=requiredPlan(hintRecord.getPlanId());FundProjectBudget b=requiredLockedBudget(hintPlan.getTopicId());FundAllocationPlan p=requiredLockedPlan(hintRecord.getPlanId(),hintPlan.getTopicId());FundAllocationRecord old=requiredLockedRecord(id,p.getPlanId());assertRunning(p);assertOperate(p);assertOwn(old.getSubmitUserId());BigDecimal after=nz(recordMapper.sumByTopicId(p.getTopicId())).subtract(nz(old.getAmount()));assertAllocationTotals(after,nz(useRecordMapper.sumByTopicId(p.getTopicId())),b.getTotalAmount());enrichAttachments(old);int rows=recordMapper.deleteById(id);if(rows>0){attachmentService.deleteByBusiness(ALLOCATION_RECORD,id);audit.record(p.getTopicId(),ALLOCATION_RECORD,id,DELETE_RECORD,old,null,null);}return rows;}
 public FundFinishCheckVo finishCheck(Long id){FundAllocationPlan p=requiredPlan(id);permissionService.assertCanFinishAllocation(p,SecurityUtils.getUserId());return calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));}
 @Transactional(isolation=Isolation.READ_COMMITTED) public void finish(Long id,FundFinishRequest request){FundAllocationPlan hint=requiredPlan(id);FundProjectBudget b=requiredLockedBudget(hint.getTopicId());FundAllocationPlan p=requiredLockedPlan(id,hint.getTopicId());assertRunning(p);permissionService.assertCanFinishAllocation(p,SecurityUtils.getUserId());assertAllocationTotals(nz(recordMapper.sumByTopicId(p.getTopicId())),nz(useRecordMapper.sumByTopicId(p.getTopicId())),b.getTotalAmount());FundFinishCheckVo c=calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));String reason=finishReason(c,request);planMapper.finish(id,c.getActualAmount(),c.getDifferenceAmount(),c.getFinishType(),reason,SecurityUtils.getUserId(),SecurityUtils.getUsername());audit.record(p.getTopicId(),ALLOCATION_PLAN,id,CLOSE_ALLOCATION,p,planMapper.selectById(id),reason);}
 private void validatePlanAmount(Long topicId,Long exclude,BigDecimal amount,BigDecimal total){validateAmount(amount);BigDecimal existing=nz(planMapper.sumPlanAmount(topicId,exclude));BigDecimal after=existing.add(amount);if(after.compareTo(total)>0)throw new ServiceException("拨付计划总额不能超过课题总资金。当前已计划："+existing+"，本次："+amount+"，课题总资金："+total);}
 private void assertAllocationFieldsUnlocked(FundAllocationPlan old,FundAllocationPlan changed){if(recordMapper.countByPlanId(old.getPlanId())==0)return;if(!sameAmount(old.getPlanAmount(),changed.getPlanAmount())||!Objects.equals(old.getAllocationDeptId(),changed.getAllocationDeptId())||!Objects.equals(old.getReceiveDeptId(),changed.getReceiveDeptId()))throw new ServiceException("计划已有拨付记录，不能修改计划金额、拨付单位或接收单位");}
 private void enrichDepts(FundAllocationPlan p){if(!researchService.isGroupUnit(p.getTopicId(),p.getAllocationDeptId())||!researchService.isGroupUnit(p.getTopicId(),p.getReceiveDeptId()))throw new ServiceException("拨付和接收单位必须属于当前课题");FundDeptOption a=org.getDept(p.getAllocationDeptId());FundDeptOption r=org.getDept(p.getReceiveDeptId());p.setAllocationDeptName(a.getDeptName());p.setReceiveDeptName(r.getDeptName());}
 private void assertOperate(FundAllocationPlan p){permissionService.assertCanOperateAllocation(p,SecurityUtils.getUserId());}
 private FundAllocationPlan enrichTopic(FundAllocationPlan p){if(p!=null)p.setTopicName(researchService.getGroup(p.getTopicId()).getGroupName());return p;}
 private FundAllocationPlan enrichPlan(FundAllocationPlan p){if(p==null)return null;enrichTopic(p);BigDecimal actual=nz(recordMapper.sumByPlanId(p.getPlanId()));p.setActualAmount(actual);p.setDifferenceAmount(actual.subtract(p.getPlanAmount()));Long userId=SecurityUtils.getUserId();boolean running=FundConstants.STATUS_RUNNING.equals(p.getStatus());p.setCanSubmitRecord(running&&permissionService.canOperateAllocation(p,userId));p.setCanAssignResponsible(running&&permissionService.canAssignAllocation(p,userId));p.setCanFinish(running&&permissionService.canFinishAllocation(p,userId));return p;}
 private FundAllocationRecord enrichAttachments(FundAllocationRecord record){if(record!=null)record.setAttachments(attachmentService.selectByBusiness(ALLOCATION_RECORD,record.getRecordId()));return record;}
 private void assertOwn(Long uid){permissionService.assertOwnRecord(uid,SecurityUtils.getUserId());}
 private void assertNoLegacyVoucherUrls(String urls){if(urls!=null&&!urls.trim().isEmpty())throw new ServiceException("附件必须先通过资金附件上传接口获取凭证");}
 private FundProjectBudget requiredLockedBudget(Long topicId){FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(topicId);if(b==null)throw new ServiceException("课题总资金配置不存在");return b;}
 private FundAllocationPlan requiredLockedPlan(Long planId,Long topicId){FundAllocationPlan p=planMapper.selectForUpdate(planId);if(p==null||!Objects.equals(topicId,p.getTopicId()))throw new ServiceException("拨付计划不存在或已发生变更");return p;}
 private FundAllocationRecord requiredRecord(Long recordId){FundAllocationRecord r=recordMapper.selectById(recordId);if(r==null)throw new ServiceException("拨付记录不存在");return r;}
 private FundAllocationRecord requiredLockedRecord(Long recordId,Long planId){FundAllocationRecord r=recordMapper.selectForUpdate(recordId);if(r==null||!Objects.equals(planId,r.getPlanId()))throw new ServiceException("拨付记录不存在或已发生变更");return r;}
 private void assertAllocationTotals(BigDecimal actualAllocation,BigDecimal actualUse,BigDecimal total){if(actualAllocation.compareTo(total)>0)throw new ServiceException("项目实际拨付总额"+actualAllocation+"元超过课题总资金"+total+"元");if(actualAllocation.compareTo(actualUse)<0)throw new ServiceException("调整后项目实际拨付"+actualAllocation+"元将低于当前实际使用"+actualUse+"元");}
 private FundAllocationPlan requiredPlan(Long id){FundAllocationPlan p=planMapper.selectById(id);if(p==null)throw new ServiceException("拨付计划不存在");return p;} private void assertRunning(FundAllocationPlan p){if(FundConstants.STATUS_FINISHED.equals(p.getStatus()))throw new ServiceException("计划已结束，不能再修改");}
 private void assertAdmin(){permissionService.assertAdmin("维护拨付计划");} private void validateAmount(BigDecimal a){if(a==null||a.compareTo(BigDecimal.ZERO)<=0)throw new ServiceException("金额必须大于0");} private BigDecimal nz(BigDecimal x){return x==null?BigDecimal.ZERO:x;}
 private boolean sameAmount(BigDecimal left,BigDecimal right){return left==null?right==null:right!=null&&left.compareTo(right)==0;}
 private String finishReason(FundFinishCheckVo check,FundFinishRequest request){boolean confirm=request!=null&&Boolean.TRUE.equals(request.getConfirmDifference());String reason=request==null||request.getReason()==null?null:request.getReason().trim();if(check.isNeedConfirm()&&!confirm)throw new ServiceException(message(check));if(check.isNeedConfirm()&&(reason==null||reason.isEmpty()))throw new ServiceException("实际拨付金额与计划不一致时，结束原因必填");if(reason!=null&&reason.length()>500)throw new ServiceException("结束原因不能超过500个字符");return reason==null||reason.isEmpty()?null:reason;}
 private String display(FundUserOption u){return u.getNickName()==null||u.getNickName().isEmpty()?u.getUserName():u.getNickName();}
 private FundFinishCheckVo calc(BigDecimal plan,BigDecimal actual){actual=nz(actual);FundFinishCheckVo v=new FundFinishCheckVo();v.setPlanAmount(plan);v.setActualAmount(actual);BigDecimal diff=actual.subtract(plan);v.setDifferenceAmount(diff);int c=diff.compareTo(BigDecimal.ZERO);v.setFinishType(c==0?FundConstants.FINISH_NORMAL:(c<0?FundConstants.FINISH_UNDER:FundConstants.FINISH_OVER));v.setNeedConfirm(c!=0);return v;}
 private String message(FundFinishCheckVo v){if(FundConstants.FINISH_UNDER.equals(v.getFinishType()))return "还有余额("+v.getDifferenceAmount().abs()+"元)未拨付，确认后可结束";return "实际拨付超出计划("+v.getDifferenceAmount().abs()+"元)，确认后可结束";}
}
