package com.ruoyi.fund.service.impl;
import java.math.BigDecimal; import java.util.List;
import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.ruoyi.common.core.exception.ServiceException; import com.ruoyi.common.security.utils.SecurityUtils; import com.ruoyi.fund.util.FundSecurityUtils; import com.ruoyi.fund.constant.FundConstants; import com.ruoyi.fund.domain.*; import com.ruoyi.fund.domain.vo.FundFinishCheckVo; import com.ruoyi.fund.mapper.*; import com.ruoyi.fund.service.*; import com.ruoyi.system.api.domain.FundUserOption;
@Service
public class FundUseServiceImpl implements IFundUseService {
 @Autowired private FundUsePlanMapper planMapper; @Autowired private FundUseRecordMapper recordMapper; @Autowired private FundProjectBudgetMapper budgetMapper; @Autowired private IFundResearchService researchService; @Autowired private IFundOrgService org;
 public List<FundUsePlan> selectPlanList(FundUsePlan q){if(q.getTopicId()==null)throw new ServiceException("请选择课题");researchService.assertGroupMember(q.getTopicId(),SecurityUtils.getUserId());List<FundUsePlan> list=planMapper.selectList(q);for(FundUsePlan p:list)enrichTopic(p);return list;} public FundUsePlan selectPlan(Long id){FundUsePlan p=required(id);researchService.assertGroupMember(p.getTopicId(),SecurityUtils.getUserId());return enrichTopic(p);}
 @Transactional public int insertPlan(FundUsePlan p){researchService.assertGroupLeader(p.getTopicId(),SecurityUtils.getUserId());FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(p.getTopicId());if(b==null)throw new ServiceException("请先配置课题总资金");validatePlanAmount(p.getTopicId(),null,p.getPlanAmount(),b.getTotalAmount());enrichResponsible(p);p.setBudgetId(b.getBudgetId());p.setStatus(FundConstants.STATUS_RUNNING);p.setCreateBy(SecurityUtils.getUsername());return planMapper.insert(p);}
 @Transactional public int updatePlan(FundUsePlan p){FundUsePlan old=planMapper.selectForUpdate(p.getUsePlanId());if(old==null)throw new ServiceException("使用计划不存在");assertRunning(old);researchService.assertGroupLeader(old.getTopicId(),SecurityUtils.getUserId());FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(old.getTopicId());if(b==null)throw new ServiceException("请先配置课题总资金");p.setTopicId(old.getTopicId());validatePlanAmount(old.getTopicId(),old.getUsePlanId(),p.getPlanAmount(),b.getTotalAmount());enrichResponsible(p);p.setUpdateBy(SecurityUtils.getUsername());return planMapper.update(p);}
 @Transactional public int deletePlan(Long id){FundUsePlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("使用计划不存在");assertRunning(p);researchService.assertGroupLeader(p.getTopicId(),SecurityUtils.getUserId());if(recordMapper.countByPlanId(id)>0)throw new ServiceException("已有使用记录，不能删除计划");return planMapper.deleteById(id);}
 public List<FundUseRecord> selectRecords(Long id){FundUsePlan p=required(id);researchService.assertGroupMember(p.getTopicId(),SecurityUtils.getUserId());return recordMapper.selectByPlanId(id);}
 @Transactional public int insertRecord(FundUseRecord r){FundUsePlan p=planMapper.selectForUpdate(r.getUsePlanId());if(p==null)throw new ServiceException("使用计划不存在");assertRunning(p);assertOperate(p);validateAmount(r.getAmount());r.setSubmitUserId(SecurityUtils.getUserId());r.setSubmitUserName(SecurityUtils.getUsername());r.setCreateBy(SecurityUtils.getUsername());return recordMapper.insert(r);}
 @Transactional public int updateRecord(FundUseRecord r){FundUseRecord old=recordMapper.selectById(r.getUseRecordId());if(old==null)throw new ServiceException("使用记录不存在");FundUsePlan p=planMapper.selectForUpdate(old.getUsePlanId());assertRunning(p);assertOwn(old.getSubmitUserId());validateAmount(r.getAmount());r.setUpdateBy(SecurityUtils.getUsername());return recordMapper.update(r);}
 @Transactional public int deleteRecord(Long id){FundUseRecord old=recordMapper.selectById(id);if(old==null)return 0;FundUsePlan p=planMapper.selectForUpdate(old.getUsePlanId());assertRunning(p);assertOwn(old.getSubmitUserId());return recordMapper.deleteById(id);}
 public FundFinishCheckVo finishCheck(Long id){FundUsePlan p=required(id);assertOperate(p);return calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));}
 @Transactional public void finish(Long id,boolean confirm){FundUsePlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("使用计划不存在");assertRunning(p);assertOperate(p);FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(p.getTopicId());if(b==null)throw new ServiceException("课题总资金配置不存在");BigDecimal projectActual=nz(recordMapper.sumByTopicId(p.getTopicId()));if(projectActual.compareTo(b.getTotalAmount())>0)throw new ServiceException("项目实际使用总额不能超过课题总资金。当前实际使用："+projectActual+"，课题总资金："+b.getTotalAmount());FundFinishCheckVo c=calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));if(c.isNeedConfirm()&&!confirm)throw new ServiceException(message(c));planMapper.finish(id,c.getActualAmount(),c.getDifferenceAmount(),c.getFinishType(),SecurityUtils.getUserId(),SecurityUtils.getUsername());}
 private void enrichResponsible(FundUsePlan p){if(p.getResponsibleUserId()==null){p.setResponsibleUserName(null);return;} if(!researchService.isGroupMember(p.getTopicId(),p.getResponsibleUserId()))throw new ServiceException("责任人必须是当前课题成员");FundUserOption u=org.getUser(p.getResponsibleUserId());p.setResponsibleUserName(u.getNickName()==null||u.getNickName().isEmpty()?u.getUserName():u.getNickName());}
 private void assertOperate(FundUsePlan p){Long uid=SecurityUtils.getUserId();if(FundSecurityUtils.isSystemAdmin())return;if(p.getResponsibleUserId()!=null){if(!uid.equals(p.getResponsibleUserId()))throw new ServiceException("该计划已指定责任人，仅责任人可操作");}else researchService.assertGroupMember(p.getTopicId(),uid);}
 private FundUsePlan enrichTopic(FundUsePlan p){if(p!=null)p.setTopicName(researchService.getGroup(p.getTopicId()).getGroupName());return p;}
 private void validatePlanAmount(Long topicId,Long excludeUsePlanId,BigDecimal amount,BigDecimal total){validateAmount(amount);BigDecimal existing=nz(planMapper.sumPlanAmount(topicId,excludeUsePlanId));BigDecimal after=existing.add(amount);if(after.compareTo(total)>0)throw new ServiceException("使用计划总额不能超过课题总资金。当前其他有效计划："+existing+"，本次："+amount+"，课题总资金："+total);}
 private void assertOwn(Long uid){if(!FundSecurityUtils.isSystemAdmin()&&!SecurityUtils.getUserId().equals(uid))throw new ServiceException("只能修改或删除本人提交的记录");}
 private FundUsePlan required(Long id){FundUsePlan p=planMapper.selectById(id);if(p==null)throw new ServiceException("使用计划不存在");return p;} private void assertRunning(FundUsePlan p){if(FundConstants.STATUS_FINISHED.equals(p.getStatus()))throw new ServiceException("计划已结束，不能再修改");} private void validateAmount(BigDecimal a){if(a==null||a.compareTo(BigDecimal.ZERO)<=0)throw new ServiceException("金额必须大于0");}
 private BigDecimal nz(BigDecimal x){return x==null?BigDecimal.ZERO:x;} private FundFinishCheckVo calc(BigDecimal plan,BigDecimal actual){actual=nz(actual);FundFinishCheckVo v=new FundFinishCheckVo();v.setPlanAmount(plan);v.setActualAmount(actual);BigDecimal diff=actual.subtract(plan);v.setDifferenceAmount(diff);int c=diff.compareTo(BigDecimal.ZERO);v.setFinishType(c==0?FundConstants.FINISH_NORMAL:(c<0?FundConstants.FINISH_UNDER:FundConstants.FINISH_OVER));v.setNeedConfirm(c!=0);return v;} private String message(FundFinishCheckVo v){return v.getDifferenceAmount().compareTo(BigDecimal.ZERO)<0?"还有余额("+v.getDifferenceAmount().abs()+"元)未使用，确认后可结束":"实际使用超出计划("+v.getDifferenceAmount().abs()+"元)，确认后可强制结束";}
}
