package com.ruoyi.fund.service.impl;
import java.math.BigDecimal; import java.util.List;
import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.ruoyi.common.core.exception.ServiceException; import com.ruoyi.common.security.utils.SecurityUtils;
import com.ruoyi.fund.util.FundSecurityUtils; import com.ruoyi.fund.constant.FundConstants; import com.ruoyi.fund.domain.*; import com.ruoyi.fund.domain.vo.FundFinishCheckVo; import com.ruoyi.fund.mapper.*; import com.ruoyi.fund.service.*; import com.ruoyi.system.api.domain.*;
@Service
public class FundAllocationServiceImpl implements IFundAllocationService {
 @Autowired private FundAllocationPlanMapper planMapper; @Autowired private FundAllocationRecordMapper recordMapper; @Autowired private FundProjectBudgetMapper budgetMapper; @Autowired private IFundOrgService org; @Autowired private IFundResearchService researchService;
 public List<FundAllocationPlan> selectPlanList(FundAllocationPlan q){List<FundAllocationPlan> list=planMapper.selectList(q);for(FundAllocationPlan p:list)enrichTopic(p);return list;} public FundAllocationPlan selectPlan(Long id){return enrichTopic(planMapper.selectById(id));}
 @Transactional public int insertPlan(FundAllocationPlan p){assertAdmin();FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(p.getTopicId());if(b==null)throw new ServiceException("请先配置课题总资金");enrichDepts(p);validatePlanAmount(p.getTopicId(),null,p.getPlanAmount(),b.getTotalAmount());p.setBudgetId(b.getBudgetId());p.setStatus(FundConstants.STATUS_RUNNING);p.setCreateBy(SecurityUtils.getUsername());return planMapper.insert(p);}
 @Transactional public int updatePlan(FundAllocationPlan p){assertAdmin();FundAllocationPlan old=planMapper.selectForUpdate(p.getPlanId());if(old==null)throw new ServiceException("拨付计划不存在");assertRunning(old);FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(old.getTopicId());p.setTopicId(old.getTopicId());enrichDepts(p);validatePlanAmount(old.getTopicId(),old.getPlanId(),p.getPlanAmount(),b.getTotalAmount());p.setUpdateBy(SecurityUtils.getUsername());return planMapper.update(p);}
 @Transactional public int deletePlan(Long id){assertAdmin();FundAllocationPlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("拨付计划不存在");assertRunning(p);if(recordMapper.countByPlanId(id)>0)throw new ServiceException("计划已有拨付记录，不能删除");return planMapper.deleteById(id);}
 @Transactional public int assign(Long id,Long uid){FundAllocationPlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("拨付计划不存在");assertRunning(p);Long current=SecurityUtils.getUserId();if(!FundSecurityUtils.isSystemAdmin()&&!researchService.isUnitManager(p.getTopicId(),p.getAllocationDeptId(),current))throw new ServiceException("仅课题配置的拨付单位负责人可指定责任人");String name=null;if(uid!=null){FundUserOption u=org.getUser(uid);if(!researchService.isGroupUnitMember(p.getTopicId(),p.getAllocationDeptId(),uid))throw new ServiceException("责任人必须是当前课题拨付单位成员");name=display(u);}return planMapper.assign(id,uid,name,SecurityUtils.getUsername());}
 public List<FundAllocationRecord> selectRecords(Long planId){requiredPlan(planId);return recordMapper.selectByPlanId(planId);}
 @Transactional public int insertRecord(FundAllocationRecord r){FundAllocationPlan p=planMapper.selectForUpdate(r.getPlanId());if(p==null)throw new ServiceException("拨付计划不存在");assertRunning(p);assertOperate(p);validateAmount(r.getAmount());r.setSubmitUserId(SecurityUtils.getUserId());r.setSubmitUserName(SecurityUtils.getUsername());r.setCreateBy(SecurityUtils.getUsername());return recordMapper.insert(r);}
 @Transactional public int updateRecord(FundAllocationRecord r){FundAllocationRecord old=recordMapper.selectById(r.getRecordId());if(old==null)throw new ServiceException("拨付记录不存在");FundAllocationPlan p=planMapper.selectForUpdate(old.getPlanId());assertRunning(p);assertOwn(old.getSubmitUserId());validateAmount(r.getAmount());r.setUpdateBy(SecurityUtils.getUsername());return recordMapper.update(r);}
 @Transactional public int deleteRecord(Long id){FundAllocationRecord old=recordMapper.selectById(id);if(old==null)return 0;FundAllocationPlan p=planMapper.selectForUpdate(old.getPlanId());assertRunning(p);assertOwn(old.getSubmitUserId());return recordMapper.deleteById(id);}
 public FundFinishCheckVo finishCheck(Long id){FundAllocationPlan p=requiredPlan(id);assertOperate(p);return calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));}
 @Transactional public void finish(Long id,boolean confirm){FundAllocationPlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("拨付计划不存在");assertRunning(p);assertOperate(p);FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(p.getTopicId());if(b==null)throw new ServiceException("课题总资金配置不存在");BigDecimal projectActual=nz(recordMapper.sumByTopicId(p.getTopicId()));if(projectActual.compareTo(b.getTotalAmount())>0)throw new ServiceException("项目实际拨付总额不能超过课题总资金。当前实际拨付："+projectActual+"，课题总资金："+b.getTotalAmount());FundFinishCheckVo c=calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));if(c.isNeedConfirm()&&!confirm)throw new ServiceException(message(c));planMapper.finish(id,c.getActualAmount(),c.getDifferenceAmount(),c.getFinishType(),SecurityUtils.getUserId(),SecurityUtils.getUsername());}
 private void validatePlanAmount(Long topicId,Long exclude,BigDecimal amount,BigDecimal total){validateAmount(amount);BigDecimal existing=nz(planMapper.sumPlanAmount(topicId,exclude));BigDecimal after=existing.add(amount);if(after.compareTo(total)>0)throw new ServiceException("拨付计划总额不能超过课题总资金。当前已计划："+existing+"，本次："+amount+"，课题总资金："+total);}
 private void enrichDepts(FundAllocationPlan p){if(!researchService.isGroupUnit(p.getTopicId(),p.getAllocationDeptId())||!researchService.isGroupUnit(p.getTopicId(),p.getReceiveDeptId()))throw new ServiceException("拨付和接收单位必须属于当前课题");FundDeptOption a=org.getDept(p.getAllocationDeptId());FundDeptOption r=org.getDept(p.getReceiveDeptId());p.setAllocationDeptName(a.getDeptName());p.setReceiveDeptName(r.getDeptName());}
 private void assertOperate(FundAllocationPlan p){Long uid=SecurityUtils.getUserId();if(FundSecurityUtils.isSystemAdmin())return;if(p.getResponsibleUserId()!=null){if(!uid.equals(p.getResponsibleUserId()))throw new ServiceException("该计划已指定责任人，仅责任人可操作");}else if(!researchService.isGroupUnitMember(p.getTopicId(),p.getAllocationDeptId(),uid))throw new ServiceException("仅当前课题拨付单位成员可操作未指定责任人的计划");}
 private FundAllocationPlan enrichTopic(FundAllocationPlan p){if(p!=null)p.setTopicName(researchService.getGroup(p.getTopicId()).getGroupName());return p;}
 private void assertOwn(Long uid){if(!FundSecurityUtils.isSystemAdmin()&&!SecurityUtils.getUserId().equals(uid))throw new ServiceException("只能修改或删除本人提交的记录");}
 private FundAllocationPlan requiredPlan(Long id){FundAllocationPlan p=planMapper.selectById(id);if(p==null)throw new ServiceException("拨付计划不存在");return p;} private void assertRunning(FundAllocationPlan p){if(FundConstants.STATUS_FINISHED.equals(p.getStatus()))throw new ServiceException("计划已结束，不能再修改");}
 private void assertAdmin(){if(!FundSecurityUtils.isSystemAdmin())throw new ServiceException("仅系统管理员可维护拨付计划");} private void validateAmount(BigDecimal a){if(a==null||a.compareTo(BigDecimal.ZERO)<=0)throw new ServiceException("金额必须大于0");} private BigDecimal nz(BigDecimal x){return x==null?BigDecimal.ZERO:x;}
 private String display(FundUserOption u){return u.getNickName()==null||u.getNickName().isEmpty()?u.getUserName():u.getNickName();}
 private FundFinishCheckVo calc(BigDecimal plan,BigDecimal actual){actual=nz(actual);FundFinishCheckVo v=new FundFinishCheckVo();v.setPlanAmount(plan);v.setActualAmount(actual);BigDecimal diff=actual.subtract(plan);v.setDifferenceAmount(diff);int c=diff.compareTo(BigDecimal.ZERO);v.setFinishType(c==0?FundConstants.FINISH_NORMAL:(c<0?FundConstants.FINISH_UNDER:FundConstants.FINISH_OVER));v.setNeedConfirm(c!=0);return v;}
 private String message(FundFinishCheckVo v){if(FundConstants.FINISH_UNDER.equals(v.getFinishType()))return "还有余额("+v.getDifferenceAmount().abs()+"元)未拨付，确认后可结束";return "实际拨付超出计划("+v.getDifferenceAmount().abs()+"元)，确认后可结束";}
}
