package com.ruoyi.fund.service.impl;
import static com.ruoyi.fund.constant.FundAuditConstants.*;
import java.math.BigDecimal; import java.util.List; import java.util.Objects;
import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.ruoyi.common.core.exception.ServiceException; import com.ruoyi.common.security.utils.SecurityUtils; import com.ruoyi.fund.constant.FundConstants; import com.ruoyi.fund.domain.*; import com.ruoyi.fund.domain.dto.FundFinishRequest; import com.ruoyi.fund.domain.vo.FundFinishCheckVo; import com.ruoyi.fund.mapper.*; import com.ruoyi.fund.service.*; import com.ruoyi.system.api.domain.FundUserOption;
@Service
public class FundUseServiceImpl implements IFundUseService {
 @Autowired private FundUsePlanMapper planMapper; @Autowired private FundUseRecordMapper recordMapper; @Autowired private FundAllocationRecordMapper allocationRecordMapper; @Autowired private FundProjectBudgetMapper budgetMapper; @Autowired private IFundResearchService researchService; @Autowired private IFundOrgService org; @Autowired private IFundOperationLogService audit; @Autowired private IFundAttachmentService attachmentService; @Autowired private FundPermissionService permissionService;
 public List<FundUsePlan> selectPlanList(FundUsePlan q){if(q.getTopicId()==null)throw new ServiceException("请选择课题");permissionService.assertGroupMember(q.getTopicId(),SecurityUtils.getUserId());List<FundUsePlan> list=planMapper.selectList(q);for(FundUsePlan p:list)enrichPlan(p);return list;} public FundUsePlan selectPlan(Long id){FundUsePlan p=required(id);permissionService.assertGroupMember(p.getTopicId(),SecurityUtils.getUserId());return enrichPlan(p);}
 @Transactional public int insertPlan(FundUsePlan p){permissionService.assertGroupLeader(p.getTopicId(),SecurityUtils.getUserId());FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(p.getTopicId());if(b==null)throw new ServiceException("请先配置课题总资金");validatePlanAmount(p.getTopicId(),null,p.getPlanAmount(),b.getTotalAmount());enrichResponsible(p);p.setBudgetId(b.getBudgetId());p.setStatus(FundConstants.STATUS_RUNNING);p.setCreateBy(SecurityUtils.getUsername());int rows=planMapper.insert(p);if(rows>0)audit.record(p.getTopicId(),USE_PLAN,p.getUsePlanId(),CREATE_PLAN,null,planMapper.selectById(p.getUsePlanId()),null);return rows;}
 @Transactional public int updatePlan(FundUsePlan p){FundUsePlan old=planMapper.selectForUpdate(p.getUsePlanId());if(old==null)throw new ServiceException("使用计划不存在");assertRunning(old);permissionService.assertGroupLeader(old.getTopicId(),SecurityUtils.getUserId());FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(old.getTopicId());if(b==null)throw new ServiceException("请先配置课题总资金");p.setTopicId(old.getTopicId());assertUseFieldsUnlocked(old,p);validatePlanAmount(old.getTopicId(),old.getUsePlanId(),p.getPlanAmount(),b.getTotalAmount());enrichResponsible(p);p.setUpdateBy(SecurityUtils.getUsername());int rows=planMapper.update(p);if(rows>0){FundUsePlan after=planMapper.selectById(p.getUsePlanId());audit.record(old.getTopicId(),USE_PLAN,p.getUsePlanId(),UPDATE_PLAN,old,after,null);if(!sameAmount(old.getPlanAmount(),after.getPlanAmount()))audit.record(old.getTopicId(),USE_PLAN,p.getUsePlanId(),CHANGE_PLAN_AMOUNT,old,after,null);if(!Objects.equals(old.getResponsibleUserId(),after.getResponsibleUserId()))audit.record(old.getTopicId(),USE_PLAN,p.getUsePlanId(),old.getResponsibleUserId()==null?ASSIGN_RESPONSIBLE:CHANGE_RESPONSIBLE,old,after,null);}return rows;}
 @Transactional public int deletePlan(Long id){FundUsePlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("使用计划不存在");assertRunning(p);permissionService.assertGroupLeader(p.getTopicId(),SecurityUtils.getUserId());if(recordMapper.countByPlanId(id)>0)throw new ServiceException("已有使用记录，不能删除计划");return planMapper.deleteById(id);}
 public List<FundUseRecord> selectRecords(Long id){FundUsePlan p=required(id);Long userId=SecurityUtils.getUserId();permissionService.assertGroupMember(p.getTopicId(),userId);boolean canOperate=FundConstants.STATUS_RUNNING.equals(p.getStatus())&&permissionService.canOperateUse(p,userId);List<FundUseRecord> records=recordMapper.selectByPlanId(id);for(FundUseRecord record:records){enrichAttachments(record);record.setCanEdit(canOperate&&permissionService.canEditRecord(record.getSubmitUserId(),userId));}return records;}
 @Transactional public int insertRecord(FundUseRecord r){FundUsePlan p=planMapper.selectForUpdate(r.getUsePlanId());if(p==null)throw new ServiceException("使用计划不存在");assertRunning(p);assertNotPendingForceFinish(p);assertOperate(p);validateAmount(r.getAmount());assertNoLegacyVoucherUrls(r.getVoucherUrls());FundProjectBudget b=requiredLockedBudget(p.getTopicId());BigDecimal actualAllocation=nz(allocationRecordMapper.sumByTopicId(p.getTopicId()));BigDecimal actualUse=nz(recordMapper.sumByTopicId(p.getTopicId()));assertUseTotals(actualUse.add(r.getAmount()),actualAllocation,b.getTotalAmount());String attachmentTokens=r.getAttachmentTokens();r.setVoucherUrls(null);r.setSubmitUserId(SecurityUtils.getUserId());r.setSubmitUserName(SecurityUtils.getUsername());r.setCreateBy(SecurityUtils.getUsername());int rows=recordMapper.insert(r);if(rows>0){attachmentService.consume(p.getTopicId(),USE_RECORD,r.getUseRecordId(),attachmentTokens);audit.record(p.getTopicId(),USE_RECORD,r.getUseRecordId(),CREATE_RECORD,null,enrichAttachments(recordMapper.selectById(r.getUseRecordId())),null);}return rows;}
 @Transactional public int updateRecord(FundUseRecord r){FundUseRecord old=recordMapper.selectById(r.getUseRecordId());if(old==null)throw new ServiceException("使用记录不存在");FundUsePlan p=planMapper.selectForUpdate(old.getUsePlanId());assertRunning(p);assertNotPendingForceFinish(p);assertOperate(p);assertOwn(old.getSubmitUserId());validateAmount(r.getAmount());assertNoLegacyVoucherUrls(r.getVoucherUrls());FundProjectBudget b=requiredLockedBudget(p.getTopicId());BigDecimal after=nz(recordMapper.sumByTopicId(p.getTopicId())).subtract(nz(old.getAmount())).add(r.getAmount());assertUseTotals(after,nz(allocationRecordMapper.sumByTopicId(p.getTopicId())),b.getTotalAmount());enrichAttachments(old);String attachmentTokens=r.getAttachmentTokens();r.setUpdateBy(SecurityUtils.getUsername());int rows=recordMapper.update(r);if(rows>0){attachmentService.consume(p.getTopicId(),USE_RECORD,r.getUseRecordId(),attachmentTokens);audit.record(p.getTopicId(),USE_RECORD,r.getUseRecordId(),UPDATE_RECORD,old,enrichAttachments(recordMapper.selectById(r.getUseRecordId())),null);}return rows;}
 @Transactional public int deleteRecord(Long id){FundUseRecord old=recordMapper.selectById(id);if(old==null)return 0;FundUsePlan p=planMapper.selectForUpdate(old.getUsePlanId());assertRunning(p);assertNotPendingForceFinish(p);assertOperate(p);assertOwn(old.getSubmitUserId());FundProjectBudget b=requiredLockedBudget(p.getTopicId());BigDecimal after=nz(recordMapper.sumByTopicId(p.getTopicId())).subtract(nz(old.getAmount()));assertUseTotals(after,nz(allocationRecordMapper.sumByTopicId(p.getTopicId())),b.getTotalAmount());enrichAttachments(old);int rows=recordMapper.deleteById(id);if(rows>0){attachmentService.deleteByBusiness(USE_RECORD,id);audit.record(p.getTopicId(),USE_RECORD,id,DELETE_RECORD,old,null,null);}return rows;}
 public FundFinishCheckVo finishCheck(Long id){FundUsePlan p=required(id);assertOperate(p);return calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));}
 @Transactional public void finish(Long id,FundFinishRequest request){FundUsePlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("使用计划不存在");assertRunning(p);assertNotPendingForceFinish(p);assertOperate(p);FundProjectBudget b=requiredLockedBudget(p.getTopicId());assertUseTotals(nz(recordMapper.sumByTopicId(p.getTopicId())),nz(allocationRecordMapper.sumByTopicId(p.getTopicId())),b.getTotalAmount());FundFinishCheckVo c=calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));String reason=finishReason(c,request);Long userId=SecurityUtils.getUserId();if(FundConstants.FINISH_OVER.equals(c.getFinishType())){if(permissionService.canConfirmForceFinish(p.getTopicId(),userId)){planMapper.finish(id,c.getActualAmount(),c.getDifferenceAmount(),c.getFinishType(),reason,true,userId,userId,SecurityUtils.getUsername());}else{planMapper.requestForceFinish(id,c.getActualAmount(),c.getDifferenceAmount(),reason,userId,SecurityUtils.getUsername());}audit.record(p.getTopicId(),USE_PLAN,id,FORCE_CLOSE_USE,p,planMapper.selectById(id),reason);return;}planMapper.finish(id,c.getActualAmount(),c.getDifferenceAmount(),c.getFinishType(),reason,false,userId,null,SecurityUtils.getUsername());audit.record(p.getTopicId(),USE_PLAN,id,CLOSE_USE,p,planMapper.selectById(id),reason);}
 @Transactional public void confirmForceFinish(Long id){FundUsePlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("使用计划不存在");assertRunning(p);if(!isPendingForceFinish(p))throw new ServiceException("该计划没有待确认的强制结束申请");Long userId=SecurityUtils.getUserId();permissionService.assertGroupLeader(p.getTopicId(),userId);FundProjectBudget b=requiredLockedBudget(p.getTopicId());assertUseTotals(nz(recordMapper.sumByTopicId(p.getTopicId())),nz(allocationRecordMapper.sumByTopicId(p.getTopicId())),b.getTotalAmount());FundFinishCheckVo c=calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));if(!FundConstants.FINISH_OVER.equals(c.getFinishType()))throw new ServiceException("当前实际使用已不再超出计划，请重新执行结束操作");planMapper.confirmForceFinish(id,c.getActualAmount(),c.getDifferenceAmount(),userId,SecurityUtils.getUsername());audit.record(p.getTopicId(),USE_PLAN,id,FORCE_CLOSE_USE,p,planMapper.selectById(id),p.getFinishReason());}
 private void enrichResponsible(FundUsePlan p){if(p.getResponsibleUserId()==null)throw new ServiceException("使用计划责任人不能为空");if(!researchService.isGroupMember(p.getTopicId(),p.getResponsibleUserId()))throw new ServiceException("责任人必须是当前课题成员");FundUserOption u=org.getUser(p.getResponsibleUserId());p.setResponsibleUserName(u.getNickName()==null||u.getNickName().isEmpty()?u.getUserName():u.getNickName());}
 private void assertOperate(FundUsePlan p){permissionService.assertCanOperateUse(p,SecurityUtils.getUserId());}
 private FundUsePlan enrichTopic(FundUsePlan p){if(p!=null)p.setTopicName(researchService.getGroup(p.getTopicId()).getGroupName());return p;}
 private FundUsePlan enrichPlan(FundUsePlan p){if(p==null)return null;enrichTopic(p);BigDecimal actual=nz(recordMapper.sumByPlanId(p.getUsePlanId()));p.setActualAmount(actual);p.setDifferenceAmount(actual.subtract(p.getPlanAmount()));Long userId=SecurityUtils.getUserId();boolean running=FundConstants.STATUS_RUNNING.equals(p.getStatus());boolean pending=isPendingForceFinish(p);p.setCanSubmitRecord(running&&!pending&&permissionService.canOperateUse(p,userId));p.setCanFinish(running&&!pending&&permissionService.canOperateUse(p,userId));p.setCanConfirmForceFinish(running&&pending&&permissionService.canConfirmForceFinish(p.getTopicId(),userId));return p;}
 private FundUseRecord enrichAttachments(FundUseRecord record){if(record!=null)record.setAttachments(attachmentService.selectByBusiness(USE_RECORD,record.getUseRecordId()));return record;}
 private void validatePlanAmount(Long topicId,Long excludeUsePlanId,BigDecimal amount,BigDecimal total){validateAmount(amount);BigDecimal existing=nz(planMapper.sumPlanAmount(topicId,excludeUsePlanId));BigDecimal after=existing.add(amount);if(after.compareTo(total)>0)throw new ServiceException("使用计划总额不能超过课题总资金。当前其他有效计划："+existing+"，本次："+amount+"，课题总资金："+total);}
 private FundProjectBudget requiredLockedBudget(Long topicId){FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(topicId);if(b==null)throw new ServiceException("课题总资金配置不存在");return b;}
 private void assertUseTotals(BigDecimal actualUse,BigDecimal actualAllocation,BigDecimal total){if(actualUse.compareTo(actualAllocation)>0)throw new ServiceException("项目实际已拨付"+actualAllocation+"元，操作后实际使用"+actualUse+"元将超过实际到账资金");if(actualUse.compareTo(total)>0)throw new ServiceException("项目实际使用总额"+actualUse+"元超过课题总资金"+total+"元");}
 private boolean isPendingForceFinish(FundUsePlan p){return "1".equals(p.getForceFinish())&&FundConstants.FINISH_OVER.equals(p.getFinishType())&&p.getFinishUserId()!=null&&p.getConfirmUserId()==null&&p.getFinishReason()!=null&&!p.getFinishReason().trim().isEmpty();}
 private void assertNotPendingForceFinish(FundUsePlan p){if(isPendingForceFinish(p))throw new ServiceException("使用计划正在等待课题负责人确认强制结束，期间不能修改记录或重复提交结束申请");}
 private void assertUseFieldsUnlocked(FundUsePlan old,FundUsePlan changed){if(recordMapper.countByPlanId(old.getUsePlanId())==0)return;if(!sameAmount(old.getPlanAmount(),changed.getPlanAmount())||!Objects.equals(old.getResponsibleUserId(),changed.getResponsibleUserId()))throw new ServiceException("计划已有使用记录，不能修改计划金额或责任人");}
 private void assertOwn(Long uid){permissionService.assertOwnRecord(uid,SecurityUtils.getUserId());}
 private void assertNoLegacyVoucherUrls(String urls){if(urls!=null&&!urls.trim().isEmpty())throw new ServiceException("附件必须先通过资金附件上传接口获取凭证");}
 private FundUsePlan required(Long id){FundUsePlan p=planMapper.selectById(id);if(p==null)throw new ServiceException("使用计划不存在");return p;} private void assertRunning(FundUsePlan p){if(FundConstants.STATUS_FINISHED.equals(p.getStatus()))throw new ServiceException("计划已结束，不能再修改");} private void validateAmount(BigDecimal a){if(a==null||a.compareTo(BigDecimal.ZERO)<=0)throw new ServiceException("金额必须大于0");}
 private BigDecimal nz(BigDecimal x){return x==null?BigDecimal.ZERO:x;} private FundFinishCheckVo calc(BigDecimal plan,BigDecimal actual){actual=nz(actual);FundFinishCheckVo v=new FundFinishCheckVo();v.setPlanAmount(plan);v.setActualAmount(actual);BigDecimal diff=actual.subtract(plan);v.setDifferenceAmount(diff);int c=diff.compareTo(BigDecimal.ZERO);v.setFinishType(c==0?FundConstants.FINISH_NORMAL:(c<0?FundConstants.FINISH_UNDER:FundConstants.FINISH_OVER));v.setNeedConfirm(c!=0);return v;} private String message(FundFinishCheckVo v){return v.getDifferenceAmount().compareTo(BigDecimal.ZERO)<0?"还有余额("+v.getDifferenceAmount().abs()+"元)未使用，确认后可结束":"实际使用超出计划("+v.getDifferenceAmount().abs()+"元)，确认后可强制结束";}
 private boolean sameAmount(BigDecimal left,BigDecimal right){return left==null?right==null:right!=null&&left.compareTo(right)==0;}
 private String finishReason(FundFinishCheckVo check,FundFinishRequest request){boolean confirm=request!=null&&Boolean.TRUE.equals(request.getConfirmDifference());String reason=request==null||request.getReason()==null?null:request.getReason().trim();if(check.isNeedConfirm()&&!confirm)throw new ServiceException(message(check));if(check.isNeedConfirm()&&(reason==null||reason.isEmpty()))throw new ServiceException("实际使用金额与计划不一致时，结束原因必填");if(reason!=null&&reason.length()>500)throw new ServiceException("结束原因不能超过500个字符");return reason==null||reason.isEmpty()?null:reason;}
}
