package com.ruoyi.fund.service.impl;
import static com.ruoyi.fund.constant.FundAuditConstants.*;
import java.math.BigDecimal; import java.util.List; import java.util.Objects;
import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.ruoyi.common.core.exception.ServiceException; import com.ruoyi.common.security.utils.SecurityUtils;
import com.ruoyi.fund.util.FundSecurityUtils; import com.ruoyi.fund.constant.FundConstants; import com.ruoyi.fund.domain.*; import com.ruoyi.fund.domain.dto.FundFinishRequest; import com.ruoyi.fund.domain.vo.FundFinishCheckVo; import com.ruoyi.fund.mapper.*; import com.ruoyi.fund.service.*; import com.ruoyi.system.api.domain.*;
@Service
public class FundAllocationServiceImpl implements IFundAllocationService {
 @Autowired private FundAllocationPlanMapper planMapper; @Autowired private FundAllocationRecordMapper recordMapper; @Autowired private FundProjectBudgetMapper budgetMapper; @Autowired private IFundOrgService org; @Autowired private IFundResearchService researchService; @Autowired private IFundOperationLogService audit; @Autowired private IFundAttachmentService attachmentService;
 public List<FundAllocationPlan> selectPlanList(FundAllocationPlan q){List<FundAllocationPlan> list=planMapper.selectList(q);for(FundAllocationPlan p:list)enrichTopic(p);return list;} public FundAllocationPlan selectPlan(Long id){return enrichTopic(planMapper.selectById(id));}
 @Transactional public int insertPlan(FundAllocationPlan p){assertAdmin();FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(p.getTopicId());if(b==null)throw new ServiceException("请先配置课题总资金");enrichDepts(p);validatePlanAmount(p.getTopicId(),null,p.getPlanAmount(),b.getTotalAmount());p.setBudgetId(b.getBudgetId());p.setStatus(FundConstants.STATUS_RUNNING);p.setCreateBy(SecurityUtils.getUsername());int rows=planMapper.insert(p);if(rows>0)audit.record(p.getTopicId(),ALLOCATION_PLAN,p.getPlanId(),CREATE_PLAN,null,planMapper.selectById(p.getPlanId()),null);return rows;}
 @Transactional public int updatePlan(FundAllocationPlan p){assertAdmin();FundAllocationPlan old=planMapper.selectForUpdate(p.getPlanId());if(old==null)throw new ServiceException("拨付计划不存在");assertRunning(old);FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(old.getTopicId());p.setTopicId(old.getTopicId());assertAllocationFieldsUnlocked(old,p);enrichDepts(p);validatePlanAmount(old.getTopicId(),old.getPlanId(),p.getPlanAmount(),b.getTotalAmount());p.setUpdateBy(SecurityUtils.getUsername());int rows=planMapper.update(p);if(rows>0){FundAllocationPlan after=planMapper.selectById(p.getPlanId());audit.record(old.getTopicId(),ALLOCATION_PLAN,p.getPlanId(),UPDATE_PLAN,old,after,null);if(!sameAmount(old.getPlanAmount(),after.getPlanAmount()))audit.record(old.getTopicId(),ALLOCATION_PLAN,p.getPlanId(),CHANGE_PLAN_AMOUNT,old,after,null);}return rows;}
 @Transactional public int deletePlan(Long id){assertAdmin();FundAllocationPlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("拨付计划不存在");assertRunning(p);if(recordMapper.countByPlanId(id)>0)throw new ServiceException("计划已有拨付记录，不能删除");return planMapper.deleteById(id);}
 @Transactional public int assign(Long id,Long uid){FundAllocationPlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("拨付计划不存在");assertRunning(p);Long current=SecurityUtils.getUserId();if(!FundSecurityUtils.isSystemAdmin()&&!researchService.isUnitManager(p.getTopicId(),p.getAllocationDeptId(),current))throw new ServiceException("仅课题配置的拨付单位负责人可指定责任人");String name=null;if(uid!=null){FundUserOption u=org.getUser(uid);if(!researchService.isGroupUnitMember(p.getTopicId(),p.getAllocationDeptId(),uid))throw new ServiceException("责任人必须是当前课题拨付单位成员");name=display(u);}int rows=planMapper.assign(id,uid,name,SecurityUtils.getUsername());if(rows>0&&!Objects.equals(p.getResponsibleUserId(),uid))audit.record(p.getTopicId(),ALLOCATION_PLAN,id,p.getResponsibleUserId()==null?ASSIGN_RESPONSIBLE:CHANGE_RESPONSIBLE,p,planMapper.selectById(id),null);return rows;}
 public List<FundAllocationRecord> selectRecords(Long planId){requiredPlan(planId);List<FundAllocationRecord> records=recordMapper.selectByPlanId(planId);for(FundAllocationRecord record:records)enrichAttachments(record);return records;}
 @Transactional public int insertRecord(FundAllocationRecord r){FundAllocationPlan p=planMapper.selectForUpdate(r.getPlanId());if(p==null)throw new ServiceException("拨付计划不存在");assertRunning(p);assertOperate(p);validateAmount(r.getAmount());r.setSubmitUserId(SecurityUtils.getUserId());r.setSubmitUserName(SecurityUtils.getUsername());r.setCreateBy(SecurityUtils.getUsername());int rows=recordMapper.insert(r);if(rows>0){attachmentService.sync(p.getTopicId(),ALLOCATION_RECORD,r.getRecordId(),r.getVoucherUrls());audit.record(p.getTopicId(),ALLOCATION_RECORD,r.getRecordId(),CREATE_RECORD,null,enrichAttachments(recordMapper.selectById(r.getRecordId())),null);}return rows;}
 @Transactional public int updateRecord(FundAllocationRecord r){FundAllocationRecord old=recordMapper.selectById(r.getRecordId());if(old==null)throw new ServiceException("拨付记录不存在");FundAllocationPlan p=planMapper.selectForUpdate(old.getPlanId());assertRunning(p);assertOwn(old.getSubmitUserId());validateAmount(r.getAmount());enrichAttachments(old);r.setUpdateBy(SecurityUtils.getUsername());int rows=recordMapper.update(r);if(rows>0){attachmentService.sync(p.getTopicId(),ALLOCATION_RECORD,r.getRecordId(),r.getVoucherUrls());audit.record(p.getTopicId(),ALLOCATION_RECORD,r.getRecordId(),UPDATE_RECORD,old,enrichAttachments(recordMapper.selectById(r.getRecordId())),null);}return rows;}
 @Transactional public int deleteRecord(Long id){FundAllocationRecord old=recordMapper.selectById(id);if(old==null)return 0;FundAllocationPlan p=planMapper.selectForUpdate(old.getPlanId());assertRunning(p);assertOwn(old.getSubmitUserId());enrichAttachments(old);int rows=recordMapper.deleteById(id);if(rows>0){attachmentService.deleteByBusiness(ALLOCATION_RECORD,id);audit.record(p.getTopicId(),ALLOCATION_RECORD,id,DELETE_RECORD,old,null,null);}return rows;}
 public FundFinishCheckVo finishCheck(Long id){FundAllocationPlan p=requiredPlan(id);assertOperate(p);return calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));}
 @Transactional public void finish(Long id,FundFinishRequest request){FundAllocationPlan p=planMapper.selectForUpdate(id);if(p==null)throw new ServiceException("拨付计划不存在");assertRunning(p);assertOperate(p);FundProjectBudget b=budgetMapper.selectByTopicIdForUpdate(p.getTopicId());if(b==null)throw new ServiceException("课题总资金配置不存在");BigDecimal projectActual=nz(recordMapper.sumByTopicId(p.getTopicId()));if(projectActual.compareTo(b.getTotalAmount())>0)throw new ServiceException("项目实际拨付总额不能超过课题总资金。当前实际拨付："+projectActual+"，课题总资金："+b.getTotalAmount());FundFinishCheckVo c=calc(p.getPlanAmount(),recordMapper.sumByPlanId(id));String reason=finishReason(c,request);planMapper.finish(id,c.getActualAmount(),c.getDifferenceAmount(),c.getFinishType(),reason,SecurityUtils.getUserId(),SecurityUtils.getUsername());audit.record(p.getTopicId(),ALLOCATION_PLAN,id,CLOSE_ALLOCATION,p,planMapper.selectById(id),reason);}
 private void validatePlanAmount(Long topicId,Long exclude,BigDecimal amount,BigDecimal total){validateAmount(amount);BigDecimal existing=nz(planMapper.sumPlanAmount(topicId,exclude));BigDecimal after=existing.add(amount);if(after.compareTo(total)>0)throw new ServiceException("拨付计划总额不能超过课题总资金。当前已计划："+existing+"，本次："+amount+"，课题总资金："+total);}
 private void assertAllocationFieldsUnlocked(FundAllocationPlan old,FundAllocationPlan changed){if(recordMapper.countByPlanId(old.getPlanId())==0)return;if(!sameAmount(old.getPlanAmount(),changed.getPlanAmount())||!Objects.equals(old.getAllocationDeptId(),changed.getAllocationDeptId())||!Objects.equals(old.getReceiveDeptId(),changed.getReceiveDeptId()))throw new ServiceException("计划已有拨付记录，不能修改计划金额、拨付单位或接收单位");}
 private void enrichDepts(FundAllocationPlan p){if(!researchService.isGroupUnit(p.getTopicId(),p.getAllocationDeptId())||!researchService.isGroupUnit(p.getTopicId(),p.getReceiveDeptId()))throw new ServiceException("拨付和接收单位必须属于当前课题");FundDeptOption a=org.getDept(p.getAllocationDeptId());FundDeptOption r=org.getDept(p.getReceiveDeptId());p.setAllocationDeptName(a.getDeptName());p.setReceiveDeptName(r.getDeptName());}
 private void assertOperate(FundAllocationPlan p){Long uid=SecurityUtils.getUserId();if(FundSecurityUtils.isSystemAdmin())return;if(p.getResponsibleUserId()!=null){if(!uid.equals(p.getResponsibleUserId()))throw new ServiceException("该计划已指定责任人，仅责任人可操作");}else if(!researchService.isGroupUnitMember(p.getTopicId(),p.getAllocationDeptId(),uid))throw new ServiceException("仅当前课题拨付单位成员可操作未指定责任人的计划");}
 private FundAllocationPlan enrichTopic(FundAllocationPlan p){if(p!=null)p.setTopicName(researchService.getGroup(p.getTopicId()).getGroupName());return p;}
 private FundAllocationRecord enrichAttachments(FundAllocationRecord record){if(record!=null)record.setAttachments(attachmentService.selectByBusiness(ALLOCATION_RECORD,record.getRecordId()));return record;}
 private void assertOwn(Long uid){if(!FundSecurityUtils.isSystemAdmin()&&!SecurityUtils.getUserId().equals(uid))throw new ServiceException("只能修改或删除本人提交的记录");}
 private FundAllocationPlan requiredPlan(Long id){FundAllocationPlan p=planMapper.selectById(id);if(p==null)throw new ServiceException("拨付计划不存在");return p;} private void assertRunning(FundAllocationPlan p){if(FundConstants.STATUS_FINISHED.equals(p.getStatus()))throw new ServiceException("计划已结束，不能再修改");}
 private void assertAdmin(){if(!FundSecurityUtils.isSystemAdmin())throw new ServiceException("仅系统管理员可维护拨付计划");} private void validateAmount(BigDecimal a){if(a==null||a.compareTo(BigDecimal.ZERO)<=0)throw new ServiceException("金额必须大于0");} private BigDecimal nz(BigDecimal x){return x==null?BigDecimal.ZERO:x;}
 private boolean sameAmount(BigDecimal left,BigDecimal right){return left==null?right==null:right!=null&&left.compareTo(right)==0;}
 private String finishReason(FundFinishCheckVo check,FundFinishRequest request){boolean confirm=request!=null&&Boolean.TRUE.equals(request.getConfirmDifference());String reason=request==null||request.getReason()==null?null:request.getReason().trim();if(check.isNeedConfirm()&&!confirm)throw new ServiceException(message(check));if(check.isNeedConfirm()&&(reason==null||reason.isEmpty()))throw new ServiceException("实际拨付金额与计划不一致时，结束原因必填");if(reason!=null&&reason.length()>500)throw new ServiceException("结束原因不能超过500个字符");return reason==null||reason.isEmpty()?null:reason;}
 private String display(FundUserOption u){return u.getNickName()==null||u.getNickName().isEmpty()?u.getUserName():u.getNickName();}
 private FundFinishCheckVo calc(BigDecimal plan,BigDecimal actual){actual=nz(actual);FundFinishCheckVo v=new FundFinishCheckVo();v.setPlanAmount(plan);v.setActualAmount(actual);BigDecimal diff=actual.subtract(plan);v.setDifferenceAmount(diff);int c=diff.compareTo(BigDecimal.ZERO);v.setFinishType(c==0?FundConstants.FINISH_NORMAL:(c<0?FundConstants.FINISH_UNDER:FundConstants.FINISH_OVER));v.setNeedConfirm(c!=0);return v;}
 private String message(FundFinishCheckVo v){if(FundConstants.FINISH_UNDER.equals(v.getFinishType()))return "还有余额("+v.getDifferenceAmount().abs()+"元)未拨付，确认后可结束";return "实际拨付超出计划("+v.getDifferenceAmount().abs()+"元)，确认后可结束";}
}
